name: testappio
description: TestApp.io SDK for Flutter
version: 1.0.0
homepage: https://testapp.io
documentation: https://github.com/testappio/flutter-sdk
repository: https://github.com/testappio/flutter-sdk

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TestAppioPlugin
